spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev
#=======================================================================================================================
  #相关Redis配置
  redis:
    database: 0         #redis索引（默认0）
    cluster:
      nodes: 
        - 192.168.1.164:6379
        - 192.168.1.165:6379
        - 192.168.1.166:6379
    password:
    timeout: 5000
    sentinel:
      master: mymaster
      nodes: 192.168.1.164:26379,192.168.1.165:26379,192.168.1.166:26379
    lettuce:
      pool:
        max-active: 8     #连接池最大连接数，使用负值没有限制
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8       #连接池中的最大空闲连接
        min-idle: 0       #连接池中的最小空闲连接
        timeout: 5000     #连接超时时间（毫秒）
#=======================================================================================================================
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411
#=======================================================================================================================
#相关eureka配置
eureka:
  instance:
    prefer-ip-address: true                    #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 10      #续约更新时间间隔（秒）
    lease-expiration-duration-in-seconds: 10   #续约到期时间（秒）
  client:
    serviceUrl:
      defaultZone: http://192.168.1.164:8761/eureka/,http://192.168.1.165:8761/eureka/,http://192.168.1.167:8761/eureka/
    healthcheck:
      enabled: true #健康检查
#=======================================================================================================================
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
#=======================================================================================================================
#Feign中开启Hystrix对服务熔断机制的AOP
feign:
  hystrix:
    enabled : true
#=======================================================================================================================

---

spring:
  profiles: test
#=======================================================================================================================
  #相关Redis配置
  redis:
    database: 0         #redis索引（默认0）
    cluster:
      nodes: 
        - 192.168.1.164:6379
        - 192.168.1.165:6379
        - 192.168.1.166:6379
    password:
    timeout: 5000
    sentinel:
      master: mymaster
      nodes: 192.168.1.164:26379,192.168.1.165:26379,192.168.1.166:26379
    lettuce:
      pool:
        max-active: 8     #连接池最大连接数，使用负值没有限制
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8       #连接池中的最大空闲连接
        min-idle: 0       #连接池中的最小空闲连接
        timeout: 5000     #连接超时时间（毫秒）
#=======================================================================================================================
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://192.168.1.166:9411
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#=======================================================================================================================
#相关eureka配置
eureka:
  instance:
    prefer-ip-address: true                    #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 10      #续约更新时间间隔（秒）
    lease-expiration-duration-in-seconds: 10   #续约到期时间（秒）
  client:
    serviceUrl:
      defaultZone: http://192.168.1.164:8761/eureka/,http://192.168.1.165:8761/eureka/,http://192.168.1.166:8761/eureka/
    healthcheck:
      enabled: true #健康检查
#=======================================================================================================================
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
#=======================================================================================================================
#Feign中开启Hystrix对服务熔断机制的AOP
feign:
  hystrix:
    enabled : true
#=======================================================================================================================

